language: node_js
sudo: false
node_js:
  - "8"
  - "10"
  - "12"
  - "14"
  - "16"
  - "18"
  - "node"
after_script: "npm install coveralls && cat ./coverage/lcov.info | ./node_modules/.bin/coveralls"
